server:
  port: 8085

spring:
  flyway:
    locations: classpath:db/migration
    fail-on-missing-locations: true

---

third-parties:
  github:
    token: token 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
  positionstack:
    token: bc02xxx

---

targeting:
  repositories:
    - questdb/questdb
#    - FeatureProbe/FeatureProbe
    - apache/dubbo
#    - assertj/assertj
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cs209;MODE=MySQL

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/cs209
    username: root
    password: cs209
  cache:
    ehcache:
      config: classpath:ehcache.xml
